python3.9 spell_correct.py data/asap_01/df.csv data/asap_01/df_spell.csv
python3.9 spell_correct.py data/asap_02/df.csv data/asap_02/df_spell.csv
python3.9 spell_correct.py data/asap_03/df.csv data/asap_03/df_spell.csv
python3.9 spell_correct.py data/asap_04/df.csv data/asap_04/df_spell.csv
python3.9 spell_correct.py data/asap_05/df.csv data/asap_05/df_spell.csv
python3.9 spell_correct.py data/asap_06/df.csv data/asap_06/df_spell.csv
python3.9 spell_correct.py data/asap_07/df.csv data/asap_07/df_spell.csv
python3.9 spell_correct.py data/asap_08/df.csv data/asap_08/df_spell.csv
python3.9 spell_correct.py data/asap_09/df.csv data/asap_09/df_spell.csv
python3.9 spell_correct.py data/asap_10/df.csv data/asap_10/df_spell.csv